### PR TITLE
Improve integration into MATE environment

### PR DESCRIPTION
**Pull request by kyrios123**
I think the following little changes would make the application better integrated into the MATE desktop environment, so I submit this proposal.

---

When you look in the control center, no MATE application name start with MATE (apart from MATE Tweak), so I propose to name it "User Management" (also I am not sure that "User Manage" sounds very well in English)
I also propose to rename the button "Close Quit" into "Close" to get consistent with the official MATE applications.

PS: Sorry but I can't update the translations in the `.po` files.

Signed-off-by: Pierre-Yves <pyu@riseup.net>

### CODE REVIEW

**Comment by zhuyaliang** [comment]
@raveit65 What do you think of this problem?

**Comment by raveit65** [comment]
I think he is right with rename the button "Close Quit" into "Close". It 's just double naming.

For the name it just depends if you plan to support other desktop or not, IHMO.
If it is mainly only for MATE i wouldn't rename it.
Other DEs like gnome or kde use their name in application names too.
And in fedora we have system-config-users, a simple tool which displays in m-c-c as `user and groups`
So, using `Mate user manager` in desktop file make it more different to the fedora tool.
For fedora i renamed the package name complete to mate-user-admin during rpm-building process.
In the end it's just a name :wink: I don't understand/think why a renaming makes a better desktop integration.

I think we had already a discussion about using manage/management here. https://github.com/mate-desktop/mate-desktop/issues/329#issuecomment-415988858
And @lukefromdc is a natural English speaker.

**Comment by kyrios123** [comment]
@raveit65 my intention is not to rename the package name or to change the name of the application, but only the change the name of the window and the name shown in the desktop shortcut. I personally think that "Users Management" (or Users & Groups Management) would integrate better as .desktop shortcut/window name to get aligned with the other applications that belong to the "Settings" category

image

For example, it's not MATE Appearance, MATE Keyboard, MATE Display, MATE Power Management, MATE Date & Time, MATE Preferred Application, ...
And that make sense because it would look weird with integrated 3rd party setting applications (Printer Settings, Firewall Configuration, Software Center, ...)

**Comment by kyrios123** [comment]
I replaced "User Management" by "Users Management" as it's like that on others DE

**Comment by Jacalz** [comment]
Users Management sounds way better than User Manage in my opinion...

**Comment by zhuyaliang** [comment]
I think it's better to use the original name.In the next version, I intend to add group management, and at that time I might consider naming. Thank you for your advice

**Comment by kyrios123** [comment]
Great, thank you!
I guess this PR can be closed then.
I'll help with the french translations once the next version will be on the track. :smiley:

**Comment by zhuyaliang** [comment]
Thank you

**Pull request closed without merging**
